config/routes.rb
Openjudge2::Application.routes.draw do
  root :to => "home#index"

  get '/home//visualization', to: redirect('/visualization')

  resources :home, :only => [:index] do
    collection do
      get :team
    end
  end

  resources :donors, :only => [:index, :show]
  resources :visualization, :only => [:index]

  resources :judges, :only => [:index, :show] do
    collection do
      get :autocomplete_judge_first_name
    end
  end

  resources :gifts, :only => [:index, :show] do
    collection do
      get :mobile
    end
  end

end

app/models/donor.rb
class Donor < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many  :gifts
  has_many  :judges, :through => :gifts

  def total_value
    self.gifts.inject(0){|sum, x| sum + (x.value||0) }
  end

  def gift_count
    self.gifts.count
  end

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :donor
  belongs_to :judge
  belongs_to :gift_type
end

app/models/gift_type.rb
class GiftType < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/judge.rb
class Judge < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many  :gifts
  has_many  :donors, :through => :gifts

  def full_name
    "#{self.first_name.titlecase}#{self.middle_name.titlecase} #{self.last_name.titlecase}"
  end

  def total_value
    self.gifts.inject(0){|sum, x| sum + (x.value||0) }
  end

  def gift_count
    self.gifts.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  caches_page :index, :show, :gzip => :best_speed
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all.sort_by { |j| j.total_value}.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
    end
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
    @donor = Donor.includes(gifts: [:judge]).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  # GET /gifts/mobile
  # GET /gifts/mobile.json
  def mobile 
    @gifts = Gift.all

    respond_to do |format|
      format.html # mobile.html.erb
      format.json
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  caches_page :index, :gzip => :best_speed
  def index
    @judges_count = Judge.all.count
    @donors_count = Donor.all.count

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/judges_controller.rb
require 'rest_client'

BASE_URL = 'http://ballotpedia.org/'
API_BASE_URL = BASE_URL + 'wiki/api.php'

class JudgesController < ApplicationController
  #TODO: Fix this autocomplete to be able to search for the full name
  autocomplete :judge, :first_name, :full => true, :extra_data => [:last_name], :display_value => :full_name
  caches_page :index, :gzip => :best_speed
  # GET /judges
  # GET /judges.json
  def index
    @judges = Judge.all.sort_by { |j| j.total_value}.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @judges }
    end
  end

  # GET /judges/1
  # GET /judges/1.json
  def show
    @judge = Judge.includes(gifts: [:donor]).find(params[:id])

    begin
      res = Hash.from_xml(RestClient.get API_BASE_URL, {:accept => :xml,
                                            :params => {
                                            :format => :xml,
                                            :action => :query,
                                            :list => :search,
                                            :srsearch => @judge.first_name + @judge.last_name
        }
      })

      @ballotpediaLink = BASE_URL + res['api']['query']['search']['p']['title'].gsub!(' ', '_')
    rescue
      logger.warn 'Searching Ballotpedia failed.'
    ensure
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @judge }
      end
    end
  end
end

app/controllers/visualization_controller.rb
class VisualizationController < ApplicationController
  caches_page :index, :gzip => :best_speed
  def index
    judges = Judge.select{ |j| j.total_value > 0 }
    .sort_by!{ |j| j.total_value * -1 }
    donors = Donor.select{ |d| d.total_value > 0 }
    .sort_by!{ |d| d.total_value * -1 }

    gon.maxTotalValue = [judges.first.total_value, donors.first.total_value].max

    gon.judges = Hash[judges
      .map! { |j| [j.id, {'id' => j.id,
        'name' => j.full_name,
        'group' => 2,
        'totalValue' => j.total_value,
        'giftCount' => j.gift_count,
        'url' => judge_path(j)
      }]}
    ]

    gon.donors = Hash[donors
        .map! { |d| [d.id, { 'id' => d.id,
          'name' => d.name,
          'group' => 1,
          'totalValue' => d.total_value,
          'giftCount' => d.gift_count,
          'url' => donor_path(d)
        }]
      }
    ]

    gon.dateFrequency = Hash[Gift.where('date_given IS NOT NULL')
      .count(:group => ["DATE(date_given)"])
      .map {|k, v| [DateTime.parse(k).strftime('%s'), v] }]

    gon.links = Gift.where('judge_id IS NOT NULL AND donor_id IS NOT NULL AND value IS NOT NULL')
      .map! { |g| {'source' => g.donor_id, 'target' => g.judge_id, 'value' => g.value }}

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    "active" if current_page?(path)
  end

  def javascript(*files)
    content_for(:head) { javascript_include_tag(*files) }
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/judges_helper.rb
module JudgesHelper
end

app/helpers/visualization_helper.rb
module VisualizationHelper
end

app/views/donors/index.html.erb
<div class="container">
  <h2>All Donors</h2>
  <p>All donors in our database sorted by total gift donations.</p>
  <div class="row">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Affiliation</th>
        <th>Total Gift Donations</th>
        <th>Number of Donations</th>
      </tr>
      </thead>
      <tbody>
      <% for @donor in @donors %>
        <tr>
          <td><%= link_to "#{@donor.name.titlecase}", donor_path(@donor)  %></td>
          <td>
            <% unless @donor.affiliation.nil? %>
              <%= "#{@donor.affiliation.titlecase}" %>
            <% end %>
          </td>
          <td><%= number_to_currency @donor.total_value %></td>
          <td><%= "#{@donor.gift_count}" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/donors/show.html.erb
<div class="container">
  <h2>
    <%= "#{@donor.name.titlecase}" %>
      <% unless @donor.affiliation.nil? %>
        (<%= "#{@donor.affiliation.titlecase}" %>)
      <% end %>
  </h2>
  <div class="row">
    <h4>Gifts Donated (<%= number_to_currency "#{@donor.total_value}" %>) </h4>
    <table class="table table-hover">
      <tr>
        <th>Description</th>
        <th>Date Given</th>
        <th>Value</th>
        <th>Judge</th>
      </tr>
      </thead>
      <tbody>
      <% for @gift in @donor.gifts %>
          <tr>
            <td><%= "#{@gift.description.titlecase}" %></td>
            <td>
              <% unless @gift.date_given.nil? %>
                <%= "#{@gift.date_given.to_formatted_s(:long)}" %>
              <% end %>
            </td>
            <td><%= number_to_currency "#{@gift.value}" %></td>
            <td><%= link_to "#{@gift.judge.full_name}", judge_path(@gift.judge.id) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<div class="home container">
    <div class="hero-unit">
        <h1>
            OpenJudge
        </h1>
        <div>
            <strong>
            An effort to bring increased visibility into <span style="color:#d62728">gift income of judges in California</span></br>
            Winner of the <a target="_blank" href="https://www.codeforamerica.org/blog/2012/11/27/unlocking-new-value-from-government-data/">2012 Data DeathMatch Hackathon </a> hosted by <a target="_blank" href="https://www.codeforamerica.org/">Code for America</a>
            </br>
            </strong>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="span4">
            <h2>Judges</h2>
            <p>Review all <%= "#{@judges_count}" %> judges currently in our database.</p>
            <%= link_to "View Judges", judges_path, :class=>"btn" %>
        </div>
        <div class="span4">
            <h2>Donors</h2>
            <p>Review all <%= "#{@donors_count}" %> donors currently in our database.</p>
            <%= link_to "View Donors", donors_path, :class=>"btn" %>
        </div>
        <div class="span4">
            <h2>Visualizations</h2>
            <p>See the connections between donors and judges.</p>
            <%= link_to "View Visualizations", visualization_index_path, :class=>"btn" %>
        </div>
    </div>
</div>

app/views/home/team.html.erb
<div class="container marketing">
    <h2> Meet the Open Judge Civic Geek Squad</h2>

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="span3 teamb">
            <%= image_tag "cait.jpg" %>
            <h4>Cathryn Posey</h4>
            <ul class="unstyled">
                <li><i class="icon-user icon-large"></i>Brand and design concepts</li>
                <li><i class="icon-twitter icon-large"></i> <a href="http://twitter.com/catpoetry">@catpoetry</a></li>
            </ul>
        </div>
        <!-- /.span3 -->

        <div class="span3 teamb">
            <%= image_tag "ed.jpg" %>
            <h4>Edward Ng</h4>
            <ul class="unstyled">
                <li><i class="icon-user icon-large"></i>Full-stack</li>
                <li><i class="icon-twitter icon-large"></i><a href="http://twitter.com/edjng">@edjng</a>
                </li>
            </ul>
        </div>
        <!-- /.span3 -->

        <div class="span3 teamb">
            <%= image_tag "kamil.jpg" %>
            <h4>Kamil Pilch</h4>
            <ul class="unstyled">
                <li><i class="icon-user icon-large"></i>Backend</li>
                <li><i class="icon-twitter icon-large"></i>Not On Twitter...</li>
            </ul>
        </div>
        <!-- /.span3 -->

        <div class="span3 teamb">
            <%= image_tag "kaming.jpg" %>
            <h4>Kaming Li</h4>
            <ul class="unstyled">
                <li><i class="icon-user icon-large"></i>iOS Developer</li>
                <li><i class="icon-twitter icon-large"></i> <a href="http://twitter.com/mimi_sf">@mimi_sf</a></li>
            </ul>
        </div>
        <!-- /.span3 -->

        <div class="span3 teamb">
            <%= image_tag "renee.jpg" %>
            <h4>Renee DiResta</h4>
            <ul class="unstyled">
                <li><i class="icon-user icon-large"></i>Data Viz</li>
                <li><i class="icon-twitter icon-large"></i><a href="http://twitter.com/noupside"> @noupside</a></li>
                </a>
            </ul>
        </div>
        <!-- /.span3 -->

        <div class="span3 teamb">
            <%= image_tag "wayne.jpg" %>
            <h4>Wayne Sutton</h4>
            <ul class="unstyled">
                <li><i class="icon-user icon-large"></i> UI/UX Designer</li>
                <li><i class="icon-twitter icon-large"></i> <a href="http://twitter.com/waynesutton">WayneSutton</a>
                </li>

            </ul>
        </div>
        <!-- /.span3 -->
    </div>
</div>

app/views/home/visualization.html.erb
<div class="container">
    <h2>
      Visualizations
    </h2>
    <p>
      Below is a network graph showing the connection between judges (red) and donors (blue) in our database.
      The width of the link represents the relative amount donated. Hover over the nodes for more information.
    </p>
    <div id="chart"></div>
    <p>
        Below is the list of the most frequently used words in proportion to their size.
    </p>
    <div class="span5">
      <%= image_tag "cadatawordie.png" %>
    </div>
</div>

app/views/judges/_form.html.erb
<%= form_for(@judge) do |f| %>
  <% if @judge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@judge.errors.count, "error") %> prohibited this judge from being saved:</h2>

      <ul>
      <% @judge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/judges/index.html.erb
<div class="container">
  <h2>All Judges</h2>
  <p>All judges in our database sorted by total gift income.</p>
  <div class="row">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Agency</th>
        <th>Total Gift Income</th>
        <th>Number of Gifts Recieved</th>
      </tr>
      </thead>
      <tbody>
      <% for @judge in @judges %>
        <tr>
          <td><%= link_to "#{@judge.full_name}", judge_path(@judge) %></td>
          <td><%= "#{@judge.agency.titlecase}" %></td>
          <td><%= number_to_currency @judge.total_value %></td>
          <td><%= "#{@judge.gift_count}" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/judges/show.html.erb
<div class="container">
  <div>
    <h2>
      <%= "#{@judge.full_name}" %>
      <% unless @ballotpediaLink.nil? %>
        <small>
          (<a target="_blank" href=<%= "#{@ballotpediaLink}" %>>Ballotpedia</a>)
        </small>
      <% end %>
    </h2>
  </div>
  <div class="row">
    <table class="table table-condensed">
      <tbody>
        <tr>
          <td>Agency:</td>
          <td><%= "#{@judge.agency.titlecase}" %></td>
        </tr>
        <tr>
          <td>Position:</td>
          <td><%= "#{@judge.position.titlecase}" %></td>
        </tr>
        <tr>
          <td>Division:</td>
          <td><%= "#{@judge.division.titlecase}" %></td>
        </tr>
      </tbody>
    </table>
    <h4>Gifts Recieved (<%= number_to_currency "#{@judge.total_value}" %>) </h4>
    <table class="table table-hover">
      <tr>
        <th>Description</th>
        <th>Date Given</th>
        <th>Value</th>
        <th>Donor</th>
      </tr>
      </thead>
      <tbody>
      <% for @gift in @judge.gifts %>
          <tr>
            <td><%= "#{@gift.description.titlecase}" %></td>
            <td>
              <% unless @gift.date_given.nil? %>
                <%= "#{@gift.date_given.to_formatted_s(:long)}" %>
              <% end %>
            </td>
            <td><%= number_to_currency "#{@gift.value}" %></td>
            <td><%= link_to "#{@gift.donor.name.titlecase}", donor_path(@gift.donor.id) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>OpenJudge</title>
        <%= include_gon %>
        <%= stylesheet_link_tag "application", :media => "all" %>
        <%= javascript_include_tag "application", "html5shiv-printshiv"  %>
        <%= csrf_meta_tags %>
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,600,300,800,700,400italic|PT+Serif:400,400italic"/>

        <!-- Fav and touch icons -->
        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-57-precomposed.png">
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-551710e428d3ca4b" async="async"></script>

        <%= yield :head %>

    </head>

    <body class="<%= controller_name %> <%= action_name %>">
    <%= render "shared/navbar" %>
        <div id="wrap">
            <div id="main">
                <%= yield %>
            </div>
        </div>

    <%= render "shared/footer" %>
    </body>
</html>

app/views/shared/_footer.erb
<!-- FOOTER -->
<footer>
    <div class="container">
        <p><a href="http://codeforamerica.org"><%= image_tag "cfalogo.png" %></a></p>
        <p><a href="#abouttext" data-toggle="modal">About</a></p>
    </div>
</footer>

app/views/shared/_navbar.erb
<!-- NAVBAR
        ================================================== -->
<!-- Wrap the .navbar in .container to center it on the page and provide easy way to target it with .navbar-wrapper. -->
<header>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="/"><%= image_tag "openjudgelogo.png" %></a>

                <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->

                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class=<%= cp(root_path) %>><%= link_to "Home", root_path%></li>
                        <li class=<%= cp(judges_path) %>><%= link_to "Judges", judges_path %></li>
                        <li class=<%= cp(donors_path) %>><%= link_to "Donors", donors_path %></li>
                        <li class=<%= cp(visualization_index_path) %>><%= link_to "Visualizations", visualization_index_path %></li>
                        <li class=<%= cp(team_home_index_path) %>><%= link_to "Team", team_home_index_path %></li>
                    </ul>
                    <!--/.nav-collapse -->
                </div>

                <!-- start search box -->
                <div class="searchboxright">
                    <%= form_tag 'judges/index', :method => :get do %>
                        <%= autocomplete_field_tag 'id', '', autocomplete_judge_first_name_judges_path, :placeholder => "Search for a Judge..." %>
                    <% end %>
                </div>
                <!-- /.navbar-inner -->
            </div>
            <!-- /.navbar -->
        </div>
        <!-- /.container -->
    </div>

    <div id="abouttext" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="aboutModal">About Open Judge</h3>
        </div>
        <div class="modal-body">
            <p><a href="index.html"> <%= image_tag "openjudgelogo2.png" %> </a></p>
            <h4>About:</h4>
            OpenJudge CA is a project created as a part of
            <a href="http://codeforamerica.org/about/">Code For America's </a> Data Deathmatch Hackathon (November 2, 2012 - November 3, 2012). In an
            effort to make public data more accessible, this project was powered by data from Fair Political Practice
            Commission's collection of the 2011 Statements of Economic Interests filed by many California Judges in 2012.

            <h4>Data disclaimer:</h4>
            This data is based on digitization by <a href="http://captricity.com">Captricity</a> of the 2011
            Statements of Economic Interests filings by most California Judges in 2012 and provided by the
            <a href="http://www.fppc.ca.gov">Fair Political Practices Commission</a> in an effort to increase government
            transparency. This data may be subject to errors and gaps and should not be taken as a comprehensive data-set.
            For more information on the data, visit
            <a href="http://captricity.com/datadeathmatch/">Captricity</a> or
            <a href="http://www.fppc.ca.gov">Fair Political Practices Commission</a>.
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
    </div>
</header>

app/views/visualization/index.html.erb
<% javascript 'visualization/index.js' %>

<div class="container">
  <h2>
    Visualizations
  </h2>
  <div class="row">
    <h4>
      Network Graph
    </h4>
    <p>
      Below is a network graph showing the connection between judges (red) and donors (blue) in our database.
      The thickness of the link represents the relative dollar amount gifted between the donor and the judge.
      The size of a node represents the relative dollar amount donated or recieved.
      Hover over the nodes for more information and click to go the respective page.
    </p>
    <div id="chart"></div>
  </div>

  <div class="row">
    <h4>
      Calendar Heatmap
    </h4>
    <p>
      Below is a calendar heatmap of the donations occuring through the course of 2011. Darker colors represent
      more frequent gift donations for a given date.
    </p>
    <div id="cal-heatmap"></div>
  </div>

  <div class="row">
    <h4>
      Wordle
    </h4>
    <p>
      Below is a <a target="_blank" href="http://www.wordle.net/">Wordle</a> graphic of the most frequently used words in gift descriptions. Frequency is proportional to the word size.
    </p>
    <div class="span5">
      <%= image_tag "cadatawordie.png" %>
    </div>
  </div>

</div>